local gs = require "game_state"

local frequency = 0.5
local min_y = 300
local max_y = 836

function init(self)
	self.timer = 1/frequency
end

function update(self, dt)
	if gs.state ~= GS_PLAYING then
		return
	end
	self.timer = self.timer - dt
	if self.timer <= 0 then
		self.timer = 1/frequency
		local p = go.get_position()
		p.y = vmath.lerp(math.random(), min_y, max_y)
		collectionfactory.create("#collectionfactory", p)
	end
end
