local gs = require "game_state"

function update(self, dt)
	if gs.state ~= GS_PLAYING then
		return
	end
	local p = go.get_position()
	p.x = p.x + gs.game_speed * gs.game_speed_multiplier * dt
	if p.x < -100 then
		go.delete()
	end
	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		-- TODO Add some particles 
		msg.post("/player#player", "fry_collision", {fry_id = go.get_id()})
	end
end
